services:
  muttocam-seunjeun-practice:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      muttocam-seunjeun-practice-db:
        condition: service_healthy

  muttocam-seunjeun-practice-db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
